---
# See: https://www.nginx.com/resources/wiki/start/topics/tutorials/install/
- name: Add RPM repository
  when: ansible_os_family == "RedHat"
  block:
  - name: RPM import GPG key
    rpm_key:
      key:   http://nginx.org/packages/keys/nginx_signing.key
      state: present

  - name: Add NGINX yum repository
    template:
      src:  templates/nginx_yum.repo
      dest: /etc/yum.repos.d/nginx.repo

- name: Add APT repository
  when: ansible_os_family == "Debian"
  block:
  - name: APT import GPG key
    apt_key:
      url:   http://nginx.org/packages/keys/nginx_signing.key
      state: present

  - name: Add NGINX apt repository
    template:
      src:  templates/nginx_apt.list
      dest: /etc/apt/sources.list.d/nginx.list

- name: Install NGINX
  package:
    name:  nginx
    state: present

- name: Enable NGINX service
  service:
    name:  nginx
    state: started
    enabled: yes

- name: Remove default.conf
  file:
    path:  "{{item}}"
    state: absent
  with_items:
  - /etc/nginx/conf.d/default.conf
  - /etc/nginx/sites-enabled/default
  notify: restart_nginx

- name: Copy nginx config
  template:
    src:  templates/sonarqube.conf
    dest: /etc/nginx/conf.d/
  notify: restart_nginx
