# https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/
---
- name: Import MongoDB key
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com
    id: 0C49F3730359A14518585931BC711F9BA15703C6

- name: Add MongoDB repository
  apt_repository:
    repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse
    filename: mongodb-org

- name: Install MongoDB
  apt:
    update_cache: yes
    name: "{{item}}"
    state: present
  with_items:
  - mongodb-org

- name: Start MongoDB
  systemd:
    name:  mongod
    state: started
    enabled: yes
    daemon_reload: yes
