---
- name: Install missing packages
  apt:
    name:  "{{packages}}"
    state: present
    update_cache: yes
  vars:
    packages:
    - apt-transport-https

- name: Add Grafana GPG public key
  apt_key:
    url:     https://packagecloud.io/grafana/stable/gpgkey
    keyring: /etc/apt/trusted.gpg.d/grafana.gpg
    state:   present

- name: Add Grafana apt repo (debian)
  apt_repository:
    repo:  deb https://packagecloud.io/grafana/stable/{{ansible_distribution | lower}}/ {{ansible_distribution_release}} main
    state: present
    filename: grafana
  when: ansible_distribution == 'Debian'

# HACK: all ubuntu versions are using debian/stretch
- name: Add Grafana apt repo (ubuntu)
  apt_repository:
    repo:  deb https://packagecloud.io/grafana/stable/debian/ stretch main
    state: present
    filename: grafana
  when: ansible_distribution == 'Ubuntu'

- name: Install Grafana package
  apt:
    name:  grafana
    state: present
    update_cache: yes
