# https://dev.mysql.com/doc/refman/en/mysqld.html
# The mysqld program has many options that can be specified at startup.
# For a complete list of options, run this command:
# $ mysqld --verbose --help
# To see what values a running MySQL server is using, type instead
# $ mysqladmin --user=root --password=secret variables
# --or--
# > SHOW [GLOBAL | SESSION] VARIABLES
#        [LIKE 'pattern' | WHERE expr]
---
- name: Apply default configs
  set_fact:
    mysql_config_mysqld: "{{ mysql_config_mysqld_default | combine(mysql_config_mysqld) }}"
    mysql_config_client: "{{ mysql_config_client_default | combine(mysql_config_client) }}"

- name: Remove old configs
  file:
    path:   "{{item}}"
    state:  absent
  with_items:
    - /etc/mysql
    - "{{mysql_config_file}}"
    - "{{mysql_config_include_dir}}"

- name: Ensure MySQL directories exists.
  file:
    path:   "{{ item.path }}"
    state:   directory
    recurse: yes
    owner:  "{{ item.owner | default(omit) }}"
    group:  "{{ item.group | default(omit) }}"
    mode:   "{{ item.mode  | default(omit) }}"
  notify: restart_mysql
  loop:
  - path:  "{{ mysql_config_include_dir }}"
  - path:  "/var/log/mysql"
    owner: "mysql"
    group: "adm"
    mode:  "0750"

- name: Copy my.cnf global MySQL configuration.
  template:
    src:  my.cnf
    dest: "{{ mysql_config_file }}"
  notify: restart_mysql

# TODO: use looping over blocks
# https://github.com/ansible/ansible/issues/13262
- name: MySQL configuration
  include_tasks: configure_section.yml
  loop_control:
    loop_var: mysql_config
  loop:
  - section: "mysqld"
    content: "{{mysql_config_mysqld}}"
  - section: "client"
    content: "{{mysql_config_client}}"

- name: Ensure MySQL is started and enabled on boot.
  systemd:
    name: "{{mysql_service}}"
    daemon_reload: yes
    enabled: yes
    state: started

- name: Run all notified handlers
  meta: flush_handlers
