---
- name: Import OS specific vars
  include_vars:
    file: "vars/{{ansible_os_family}}.yml"

- name: Install MySQL server
  include_tasks: "install_{{ansible_os_family}}.yml"

- name: Config MySQL daemon
  include_tasks: configure.yml

- name: Setup MySQL users
  include_tasks: users.yml
