# https://devops.profitbricks.com/tutorials/install-and-configure-apache-kafka-on-ubuntu-1604-1/
---
- name: Install JDK
  apt:
    update_cache: yes
    name: "{{ item }}"
    state: present
  with_items:
  - default-jdk   # OpenJDK
  - zookeeperd    # Apache ZooKeeper

- name: Download Kafka
  unarchive:
    remote_src: yes
    src: http://mirror.downloadvn.com/apache/kafka/0.11.0.1/kafka_2.11-0.11.0.1.tgz
    dest: /opt

- name: Rename Kafka directory
  command: mv kafka_2.11-0.11.0.1 kafka
  args:
    chdir:   /opt
    creates: /opt/kafka

- name: Configure Kafka service
  copy:
    src:  "kafka.service"
    dest: "/etc/systemd/system"
  notify: restart kafka

- name: Start Kafka
  systemd:
    name:  kafka
    state: started
    enabled: yes
    daemon_reload: yes
