version: '3.5'

services:
  database:
    image: postgres:10-alpine
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: sonar
      POSTGRES_DB: sonarbase
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 3

  sonarqube:
    image: sonarqube:7.1-alpine
    ports:
    - 9000:9000
    depends_on:
    - database
    restart: unless-stopped
    environment:
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: secret
      SONARQUBE_JDBC_URL: jdbc:postgresql://database:5432/sonarbase
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider localhost:9000/api/system/status || exit 1"]
      start_period: 15s
      interval: 15s
      timeout: 15s
      retries: 3
