---
- name: Install RabbitMQ server
  include_tasks: "install_{{ansible_os_family}}.yml"

- name: Config RabbitMQ daemon
  include_tasks: configure.yml

- name: Setup RabbitMQ plugins
  rabbitmq_plugin:
    names: "{{plugin.name}}"
    state: "{{plugin.status | default('enabled')}}"
  when: rabbitmq_plugins is defined
  loop: "{{rabbitmq_plugins}}"
  loop_control:
    loop_var: plugin

- name: Ensure RabbitMQ is running and enabled on boot
  service: 
    name: "{{rabbitmq_service}}"
    state: started
    enabled: yes

- name: Config RabbitMQ users
  rabbitmq_user:
    username:    "{{item.username}}"
    password:    "{{item.password}}"
    state:       "{{item.state | default(omit)}}"
    tags:        "{{item.tags  | default(omit)}}"
    permissions: "{{item.permissions | default(omit)}}"
  loop: "{{rabbitmq_users}}"
  when: rabbitmq_users is defined
