---
- name: Install Docker
  shell: curl -sSL https://get.docker.com/ | sudo sh
  args:
    creates: /usr/bin/docker

- name: Add users to 'docker' group
  user:
    user:   "{{item}}"
    groups: "docker"
    append: yes
  with_items: "{{docker_users | default(ansible_user)}}"
