---
- name: Import OS specific vars
  include_vars:
    file: "vars/{{ansible_os_family}}.yml"

- name: Install PostgreSQL server
  include_tasks: "install_{{ansible_os_family}}.yml"

# - name: Config PostgreSQL daemon
#   include_tasks: configure.yml

# - name: Setup PostgreSQL users
#   include_tasks: users.yml
