---
- name: Enable Redis repo for Ubuntu
  when: ansible_distribution == 'Ubuntu' and
        redis_repo_enabled | default(false)
  block:
  - name: Add Redis PPA
    apt_repository:
      repo:  ppa:chris-lea/redis-server
      state: present
      filename: redis

- name: Install Redis server
  apt:
    name: "{{ redis_package }}"
    state: present
    update_cache: true
